"""Generate assets/generated/contribution-path.svg - the animated centerpiece
that replaces the static GitHub contribution heatmap.

Reads data/contributions.json (committed by the GitHub Action on a schedule;
falls back to the sample file generated by gen_contrib_data_sample.py).
Pure CSS + SMIL animation only - no JS - so it plays correctly when the file
is embedded in the README via <img src="...">.
"""
import sys, os, json, datetime
sys.path.insert(0, os.path.dirname(__file__))
from theme import *  # noqa
from text2path import text_group

ROOT = os.path.join(os.path.dirname(__file__), "..")
with open(os.path.join(ROOT, "data", "contributions.json")) as f:
    D = json.load(f)

WEEKS, DAYS = D["weeks"], D["days_per_week"]
LEVELS = D["levels"]
START = datetime.date.fromisoformat(D["start_date"])

CELL, GAP = 12, 3
COL_W, ROW_H = CELL + GAP, CELL + GAP
GRID_X, GRID_Y = 34, 58
GRID_W = WEEKS * COL_W - GAP
GRID_H = DAYS * ROW_H - GAP
W = GRID_X + GRID_W + 36
STREET_Y = GRID_Y + GRID_H + 20
H = STREET_Y + 66

EMBER_SCALE = ["#2A2019", "#5C3A1A", EMBER_DIM, EMBER, "#FFD37A"]
MONTHS_ID = ["Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des"]


def cell_date(col, row):
    return START + datetime.timedelta(days=col * DAYS + row)


# -- header -----------------------------------------------------------------
title_g, _ = text_group("Jejak Kontribusi", FONT_DIR + "BigShoulders-Bold.ttf",
                         24, GRID_X, 30, WASHI)

# -- month labels -------------------------------------------------------------
month_labels = []
last_month = None
for c in range(WEEKS):
    d = cell_date(c, 0)
    if d.month != last_month:
        last_month = d.month
        lx = GRID_X + c * COL_W
        g, _ = text_group(MONTHS_ID[d.month - 1], FONT_DIR + "Tektur-Medium.ttf",
                           10, lx, GRID_Y - 9, MIST)
        month_labels.append(g)

# -- grid cells --------------------------------------------------------------
cells = []
peak_glows = []
for c in range(WEEKS):
    for r in range(DAYS):
        idx = c * DAYS + r
        if idx >= len(LEVELS):
            continue
        lv = LEVELS[idx]
        x = GRID_X + c * COL_W
        y = GRID_Y + r * ROW_H
        cells.append(f'<rect x="{x:.1f}" y="{y:.1f}" width="{CELL}" height="{CELL}" rx="3" '
                      f'fill="{EMBER_SCALE[lv]}"/>')
        if lv == 4:
            cx, cy = x + CELL / 2, y + CELL / 2
            peak_glows.append(
                f'<circle class="peak" cx="{cx:.1f}" cy="{cy:.1f}" r="9" fill="url(#peak-glow)"/>')

# day-of-week micro labels (Sen / Rab / Jum only, like GitHub's Mon/Wed/Fri)
day_label_rows = {0: "Min", 2: "Sel", 4: "Kam"}
day_labels = []
for r, lbl in day_label_rows.items():
    g, _ = text_group(lbl, FONT_DIR + "Tektur-Medium.ttf", 9,
                       6, GRID_Y + r * ROW_H + CELL - 2, MIST)
    day_labels.append(g)

# -- legend -------------------------------------------------------------------
LEG_X = GRID_X
legend_swatches = "".join(
    f'<rect x="{LEG_X + 34 + i * 16:.1f}" y="{STREET_Y + 46}" width="11" height="11" rx="2" '
    f'fill="{EMBER_SCALE[i]}"/>' for i in range(5))
legend_lo, _ = text_group("sepi", FONT_DIR + "Tektur-Medium.ttf", 9,
                           LEG_X, STREET_Y + 55, MIST)
legend_hi, _ = text_group("membara", FONT_DIR + "Tektur-Medium.ttf", 9,
                           LEG_X + 122, STREET_Y + 55, MIST)

# -- walking ronin sprite (single <g>, animated with CSS only) ---------------
ronin = f'''
<g class="ronin-walk">
  <g class="ronin-bob">
    <ellipse cx="0" cy="17" rx="9" ry="2.6" fill="{INK}" opacity="0.5"/>
    <circle class="lamp-glow" cx="-8" cy="2" r="7" fill="url(#peak-glow)"/>
    <rect class="leg leg-a" x="-4.5" y="6" width="3.4" height="9" rx="1.6" fill="{INK_3}"/>
    <rect class="leg leg-b" x="1.1" y="6" width="3.4" height="9" rx="1.6" fill="{INK_3}"/>
    <path d="M-6,-2 C-6,-9 6,-9 6,-2 L7,8 C7,11 -7,11 -7,8 Z" fill="{TORII_DK}"/>
    <path d="M-6,-2 C-2,1 2,1 6,-2 L6,4 C2,6 -2,6 -6,4 Z" fill="{TORII}"/>
    <path d="M2,-8 L11,-15" stroke="{GOLD}" stroke-width="1.6" stroke-linecap="round"/>
    <circle cx="0" cy="-9" r="5.4" fill="#3a281f"/>
    <path d="M-5.4,-10 C-5.4,-15 5.4,-15 5.4,-10 C3,-12.4 -3,-12.4 -5.4,-10 Z" fill="{INK}"/>
    <rect x="-9" y="-3" width="4" height="2" rx="1" fill="{EMBER}" class="scarf"/>
  </g>
</g>'''

svg = f'''<svg viewBox="0 0 {W} {H}" xmlns="http://www.w3.org/2000/svg" role="img"
     aria-label="Jejak kontribusi - {D['total_contributions']} kontribusi, streak berjalan {D['current_streak']} hari, rekor {D['longest_streak']} hari">
<defs>
  <linearGradient id="panel-bg" x1="0" y1="0" x2="0" y2="1">
    <stop offset="0%" stop-color="{INK_2}"/>
    <stop offset="100%" stop-color="{INK}"/>
  </linearGradient>
  <radialGradient id="peak-glow" cx="50%" cy="50%" r="50%">
    <stop offset="0%" stop-color="#FFD37A" stop-opacity="0.95"/>
    <stop offset="100%" stop-color="#FFD37A" stop-opacity="0"/>
  </radialGradient>
  <linearGradient id="slash" x1="0" y1="0" x2="1" y2="0">
    <stop offset="0%" stop-color="{WASHI}" stop-opacity="0"/>
    <stop offset="50%" stop-color="{WASHI}" stop-opacity="0.85"/>
    <stop offset="100%" stop-color="{WASHI}" stop-opacity="0"/>
  </linearGradient>
  <clipPath id="panel-clip"><rect x="0" y="0" width="{W}" height="{H}" rx="14"/></clipPath>
  <style>
    #contrib-path {{ --travel: {GRID_W - 4}px; }}
    .ronin-walk {{
      animation: walk 16s linear infinite;
      offset-path: none;
    }}
    @keyframes walk {{
      0%   {{ transform: translate({GRID_X + 6}px, {STREET_Y + 30}px); }}
      100% {{ transform: translate({GRID_X + GRID_W - 6}px, {STREET_Y + 30}px); }}
    }}
    .ronin-bob {{ animation: bob 0.46s ease-in-out infinite; transform-origin: 0px 17px; }}
    @keyframes bob {{ 0%,100% {{ transform: translateY(0); }} 50% {{ transform: translateY(-1.6px); }} }}
    .leg-a {{ animation: stepA 0.46s ease-in-out infinite; transform-origin: -2.8px 6px; }}
    .leg-b {{ animation: stepB 0.46s ease-in-out infinite; transform-origin: 2.8px 6px; }}
    @keyframes stepA {{ 0%,100% {{ transform: rotate(22deg); }} 50% {{ transform: rotate(-22deg); }} }}
    @keyframes stepB {{ 0%,100% {{ transform: rotate(-22deg); }} 50% {{ transform: rotate(22deg); }} }}
    .lamp-glow {{ animation: lampflick 1.1s ease-in-out infinite; }}
    @keyframes lampflick {{ 0%,100% {{ opacity:.7 }} 50% {{ opacity:1 }} }}
    .spark {{ animation: trail 16s linear infinite; opacity: 0; }}
    @keyframes trail {{
      0%   {{ transform: translate({GRID_X + 6}px, {STREET_Y + 30}px) translateY(0); opacity: 0; }}
      3%   {{ opacity: .8; }}
      8%   {{ opacity: 0; }}
      100% {{ transform: translate({GRID_X + GRID_W - 6}px, {STREET_Y + 30}px) translateY(-6px); opacity: 0; }}
    }}
    .peak {{ animation: peakpulse 2.6s ease-in-out infinite; }}
    @keyframes peakpulse {{ 0%,100% {{ opacity:.55; transform: scale(1); }} 50% {{ opacity:1; transform: scale(1.25); }} }}
    .katana-sweep {{ animation: sweep 9s ease-in-out infinite; }}
    @keyframes sweep {{
      0%   {{ transform: translateX(-120px) rotate(18deg); opacity: 0; }}
      6%   {{ opacity: .9; }}
      16%  {{ opacity: 0; }}
      100% {{ transform: translateX({GRID_W + 120}px) rotate(18deg); opacity: 0; }}
    }}
    @media (prefers-reduced-motion: reduce) {{
      .ronin-walk, .ronin-bob, .leg-a, .leg-b, .lamp-glow, .spark, .peak, .katana-sweep {{
        animation: none !important;
      }}
      .ronin-walk {{ transform: translate({GRID_X + GRID_W / 2:.0f}px, {STREET_Y + 30}px) !important; }}
    }}
  </style>
</defs>

<g clip-path="url(#panel-clip)">
<rect width="{W}" height="{H}" fill="url(#panel-bg)"/>
{title_g}
{"".join(month_labels)}
{"".join(day_labels)}
{"".join(cells)}
{"".join(peak_glows)}

<line x1="{GRID_X}" y1="{STREET_Y + 40}" x2="{GRID_X + GRID_W}" y2="{STREET_Y + 40}"
      stroke="{INK_3}" stroke-width="1.5" opacity="0.8"/>
<g class="spark" style="animation-delay:-0.55s"><circle r="1.6" fill="{EMBER}"/></g>
<g class="spark" style="animation-delay:-1.05s"><circle r="1.3" fill="{GOLD}"/></g>
<g class="spark" style="animation-delay:-1.5s"><circle r="1" fill="{EMBER}"/></g>
{ronin}

<rect class="katana-sweep" x="0" y="{GRID_Y - 6}" width="6" height="{GRID_H + 12}" fill="url(#slash)"/>

{legend_swatches}
{legend_lo}
{legend_hi}
<rect x="0.75" y="0.75" width="{W - 1.5}" height="{H - 1.5}" rx="13.5" fill="none" stroke="{INK_3}" stroke-width="1.5"/>
</g>
</svg>'''

out = os.path.join(ROOT, "assets", "generated", "contribution-path.svg")
with open(out, "w", encoding="utf-8") as f:
    f.write(svg)
print("wrote", out, len(svg), "bytes |", W, "x", H, "| months labeled:", len(month_labels))
